@startuml

!include <C4/C4_Context>

Person(user, "Пользователь", "Пользуется системой")
Person(admin, "Техспециалист", "Подключает новые устройства")

System(backend, "Теплый дом", "Монолит с Web-интерфейсом и интеграцией системами отопления")
System(heating, "Система отопления", "Совместимая система отопления")

Rel(user, backend, "Просматривает температуру и включает/выключает отопление в доме через WEB UI")
Rel(admin, backend, "Регистрирует новое устройство через WEB UI")
Rel(backend, heating, "Запрашивает температуру с датчиков")
Rel(backend, heating, "Включает/выключает отопление")

@enduml